context:
  name: refl1d
  version: 0.8.16

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/reflectometry/refl1d/archive/v${{ version }}.tar.gz
  sha256: 38ed7b8b559396972f94c0281eb901c38ecfee31b2731d8a70abc3c7dbfab3d0

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - refl1d=refl1d.main:cli
      - refl1d_gui=refl1d.main:gui
  noarch: python

requirements:
  host:
    - python <3.13 # numba does not support 3.13 yet
    - pip
    - setuptools
  run:
    - python <3.13
    - bumps >=0.7.16
    - numpy <2.0
    - scipy
    - matplotlib-base
    - periodictable
    - numba
    - wxpython

tests:
  - python:
      imports:
        - refl1d
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - refl1d -?
      - refl1d_gui -?

about:
  license: LicenseRef-PUBLIC-DOMAIN
  license_file: LICENSE.txt
  summary: "Refl1D is a program for analyzing 1D reflectometry measurements made with X-ray and neutron beamlines."
  homepage: http://github.com/reflectometry/refl1d

extra:
  recipe-maintainers:
    - MridulS
    - bmaranville
