{% set version = "24.11.2" %}

package:
  name: scipp
  version: "{{ version }}"

source:
  url: https://github.com/scipp/scipp/archive/{{ version }}.tar.gz
  sha256: 7f6b461506ebc50c8864d5e1a81b1508685f9f7c46ac080fe72868f63bf2bc20
  patches:
    - 0002-pr-3629.patch
    # - 0003-pr-3626.patch
    - 0004-pr-3628.patch

build:
  skip: true  # [py<311]
  script_env:
    - GIT_VERSION_INFO={{ version }}
  number: 0
  missing_dso_whitelist:
    - '*'        # [win]
  script:
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=$PYTHON -DCONDA_FORGE_BUILD=ON  # [unix]
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE="%PYTHON%" -DCONDA_FORGE_BUILD=ON  # [win]
    - cmake --build --preset build
    - ctest --preset test  # [build_platform == target_platform]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cmake
    - conan ==1.64.1
    - ninja
    - make  # [linux]
  host:
    - python
    - tbb-devel
    - numpy
  run:
    - python

test:
  imports:
    - scipp
  requires:
    - numba  # [py<313]
    - bs4
    - h5py
    - hypothesis
    - pandas
    - pytest
    - python-graphviz
    - scipy
    - xarray
    - ipython
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest -v tests


about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/

extra:
  recipe-maintainers:
    - MridulS
