{% set name = "scipp" %}
{% set version = "24.02.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scipp/scipp/archive/refs/tags/{{ version }}.tar.gz
  sha256: 00ce64d963a39b9a60deb460c7c73b61fc082e5fa4b0c015f54d09e87f0bc2c7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cmake
    - conan ==1.59.0
    - cppcheck  # [linux64]
    - git
    - ninja
    - python  # [build_platform != target_platform]
  host:
    - python
    - pip
    - scikit-build-core
    - setuptools_scm
    - tbb-devel {{ tbb_devel }}
  run:
    - numpy
    - python
    - tbb {{ tbb }}

test:
  imports:
    - scipp
  requires:
    - {{ compiler('cxx') }}
    - bs4
    - cmake
    - comm>=0.1.3  # earlier versions break tests with ipywidgets with latest ipykernel
    - conan==1.59.0
    - h5py
    - hypothesis
    - ipykernel
    - numba
    - numpy
    - pandas
    - pytest
    - python-graphviz
    - scipy>=1.7.0
    - tbb-devel {{ tbb_devel }}
    - xarray
    - pip
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest -v tests

about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
