{% set name = "scipp" %}
{% set version = "24.08.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/scipp/scipp/archive/{{ version }}.tar.gz
  sha256: f85d639a920a2b13415cfa2322b64eb11aaf40d929e50c748476ab01a4805219

build:
  number: 0
  script_env:
    # - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - CMAKE_GENERATOR="Ninja"
  script:
    # - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=$PYTHON  # [unix]
    # - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=%PYTHON%  # [win]
    # - cmake --build --preset build
    # - ctest --preset test  # [build_platform == target_platform]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - conan ==1.64.1
    - ninja
    - python                                 # [build_platform != target_platform]
    # - pybind11                             # [build_platform != target_platform]
    # - {{ compiler('c') }}
    # - make  # [not win]
    # - scikit-build-core
    # - cppcheck  # [linux64]
    # - git

  host:
    - python
    - pip
    - setuptools
    - scikit-build-core
    - tbb-devel {{ tbb_devel }}
    # - pybind11
    # - setuptools >=69
    # - setuptools_scm >=8
    # - toml
  run:
    - numpy
    - python
    - tbb {{ tbb }}

test:
  imports:
    - scipp
  requires:
    - {{ compiler('cxx') }}
    - bs4
    - cmake
    - comm>=0.1.3  # earlier versions break tests with ipywidgets with latest ipykernel
    - h5py
    - hypothesis
    - ipykernel
    - numba
    - numpy
    - pandas
    - pytest
    - python-graphviz
    - scipy>=1.7.0
    - tbb-devel {{ tbb_devel }}
    - xarray
    - pip
    - conan ==1.64.1
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest -v tests

about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
