{% set name = "scipp" %}
{% set version = "24.02.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4957438fdb83d9b735ee7e5e211a839f99c414fb3a55a863c0bb4e52162bc4ff

build:
  number: 0
  script:
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=$PYTHON  # [unix]
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=%PYTHON%  # [win]
    - cmake --build --preset build
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cppcheck  # [linux64]
    - git
    - ninja
    - conan ==1.59.0

  host:
    - python
    - pip
    - scikit-build-core
    - tbb-devel {{ tbb_devel }}
    - setuptools >=69
    - setuptools_scm >=8
    - toml
  run:
    - numpy
    - python
    - tbb {{ tbb }}

test:
  imports:
    - scipp
  requires:
    - {{ compiler('cxx') }}
    - bs4
    - cmake
    - comm>=0.1.3  # earlier versions break tests with ipywidgets with latest ipykernel
    - h5py
    - hypothesis
    - ipykernel
    - numba
    - numpy
    - pandas
    - pytest
    - python-graphviz
    - scipy>=1.7.0
    - tbb-devel {{ tbb_devel }}
    - xarray
    - pip
    - conan ==1.59.0
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest -v tests

about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
