{% set version = "24.11.2" %}

package:
  name: scipp
  version: "{{ version }}"

source:
  url: https://github.com/scipp/scipp/archive/{{ version }}.tar.gz
  sha256: 7f6b461506ebc50c8864d5e1a81b1508685f9f7c46ac080fe72868f63bf2bc20
  patches:
    - 0001-Use-GIT_VERSION_INFO-as-a-env-var.patch

build:
  skip: true  # [py<310]
  script_env:
    - GIT_VERSION_INFO={{ version }}
  number: 0
  script:
    - mkdir -p /home/conda/.conan/profiles && echo "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.cppstd=17\ncompiler.libcxx=libstdc++11\ncompiler.version=13\nos=Linux\nos_build=Linux\n[options]\n[build_requires]\n[env]" > /home/conda/.conan/profiles/default  # [linux]
    - echo "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\ncompiler=Visual Studio\ncompiler.cppstd=17\ncompiler.runtime=MD\ncompiler.toolset=v143\ncompiler.version=17\nos=Windows\nos_build=Windows\n[options]\n[build_requires]\n[env]" > "C:\Users\VssAdministrator\.conan\profiles\default"  # [win]
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=$PYTHON ${CMAKE_ARGS}  # [unix]
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE="%PYTHON%" "%CMAKE_ARGS%"  # [win]
    - cmake --build --preset build
    - ctest --preset test  # [build_platform == target_platform]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cmake
    - conan ==1.65.0
    - ninja
  host:
    - python
    - tbb-devel
    - numpy
  run:
    - python

test:
  imports:
    - scipp
  requires:
    - numba  # [py<313]
    - bs4
    - h5py
    - hypothesis
    - pandas
    - pytest
    - python-graphviz
    - scipy
    - xarray
    - ipython
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest -v tests


about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
