{% set name = "scipp" %}
{% set version = "24.09.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scipp/scipp/archive/{{ version }}.tar.gz
  sha256: c7589b26c03af7e88f858c965ef8d213905ab36804967e8c524db56bec63b253

build:
  number: 0
  script_env:
    - GIT_VERSION_INFO: ${{ version }}
  script:
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=$PYTHON  # [unix]
    - cmake --preset package-{{ target_platform }} -DPython_EXECUTABLE=%PYTHON%  # [win]
    - cmake --build --preset build
    - ctest --preset test  # [build_platform == target_platform]

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cmake
    - conan ==1.64.1
    - ninja
    - ccache
    - git
  host:
    - python
    - numpy
    - tbb-devel
  run:
    - python

test:
  imports:
    - scipp
  requires:
    - bs4
    - h5py
    - hypothesis
    - numba
    - pandas
    - pytest
    - python-graphviz
    - scipy
    - xarray
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest -v tests

about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
