context:
  name: scipp
  version: 24.09.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/scipp/scipp/archive/{{ version }}.tar.gz
  sha256: c7589b26c03af7e88f858c965ef8d213905ab36804967e8c524db56bec63b253

build:
  number: 0
  script:
    env:
      GIT_VERSION_INFO: ${{ version }}
    content:
      - cmake --preset package-${{ target_platform }} -DPython_EXECUTABLE=$PYTHON -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC
      - cmake --build --preset build
      - ctest --preset test
  skip:
    - match(python, "<3.10")
    - match(python, ">3.12")

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
    - cmake
    - conan ==1.65.0
    - ninja
    - ccache
    - ${{ "m2-git" if win }}
    - ${{ "git" if unix }}
    - llvm ==17.0.6
  host:
    - python
    - numpy
    - tbb-devel
    - llvm ==17.0.6
  run:
    - python

tests:
  - files:
      source:
        - pyproject.toml
        - tests/
    requirements:
      run:
        - bs4
        - h5py
        - hypothesis
        - numba
        - pandas
        - pytest
        - python-graphviz
        - scipy
        - xarray
    script:
      - python -m pytest -v tests

about:
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  license_file: LICENSE
  homepage: https://scipp.github.io/
  repository: https://github.com/scipp/scipp
  documentation: https://scipp.github.io/

extra:
  recipe-maintainers:
    - MridulS
