context:
  name: scipp
  version: 24.09.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/scipp/scipp.git
  tag: ${{ version }}

build:
  number: 0
  script:
    env:
      GIT_VERSION_INFO: ${{ version }}
    content:
      - cmake --preset package-${{ target_platform }} -DPython_EXECUTABLE=$PYTHON
      - cmake --build --preset build
      - ctest --preset test

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - cmake
    - conan ==1.64.1
    - ninja
    - if: build_platform != target_platform
      then: python
  host:
    - python <3.13
    - pip
    - scikit-build-core
    - tbb-devel ${{ tbb_devel }}
  run:
    - numpy
    - python
    - tbb ${{ tbb }}

tests:
  - python:
      imports:
        - scipp
      pip_check: true
  - files:
      source:
        - pyproject.toml
        - tests/
    requirements:
      run:
        - ${{ compiler('cxx') }}
        - bs4
        - cmake
        - comm>=0.1.3
        - h5py
        - hypothesis
        - ipykernel
        - numba
        - numpy
        - pandas
        - pytest
        - python-graphviz
        - scipy>=1.7.0
        - tbb-devel ${{ tbb_devel }}
        - xarray
        - pip
        - conan ==1.64.1
    script:
      - python -m pytest -v tests

about:
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  license_file: LICENSE
  homepage: https://scipp.github.io/
  repository: https://github.com/scipp/scipp
  documentation: https://scipp.github.io/

extra:
  recipe-maintainers:
    - MridulS
