context:
  name: scipp
  version: 24.11.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/scipp/scipp/archive/${{ version }}.tar.gz
  sha256: 7f6b461506ebc50c8864d5e1a81b1508685f9f7c46ac080fe72868f63bf2bc20
  patches:
    - patch
build:
  number: 0
  skip:
    - match(python, "<3.10")
    - match(python, ">3.12")
  script:
    env:
      GIT_VERSION_INFO: ${{ version }}
    content:
      - cmake --preset package-${{ target_platform }} -DPython_EXECUTABLE=$PYTHON $CMAKE_ARGS
      - cmake --build --preset build
      - ctest --preset test

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
    - cmake
    - conan ==1.65.0
    - ninja
    - ccache
    - ${{ "m2-git" if win }}
    - ${{ "git" if unix }}
  host:
    - python
    - numpy
    - tbb-devel
  run:
    - python

tests:
  - files:
      source:
        - pyproject.toml
        - tests/
    requirements:
      run:
        - bs4
        - h5py
        - hypothesis
        - pandas
        - pytest
        - python-graphviz
        - scipy
        - xarray
        - ipython
    script:
      - python -m pytest -v tests

about:
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  license_file: LICENSE
  homepage: https://scipp.github.io/
  repository: https://github.com/scipp/scipp
  documentation: https://scipp.github.io/

extra:
  recipe-maintainers:
    - MridulS
